### ISSUE TITLE
Add main apartment list

### ISSUE THREAD

**Issue by theo-brlle** [theo-brlle/homy#12]
### 🎯 Summary

Add the main apartment list. This should be named `HomeView`.

### 📝 Todos

- [ ] Design simple list
- [ ] Split the list into sections:
  - [ ] Favorites
  - [ ] Upcoming visits
  - [ ] Recent visits
- [ ] Add search bar
