### ISSUE TITLE
Add apartment details

### ISSUE THREAD

**Issue by theo-brlle** [theo-brlle/homy#18]
### 🎯 Summary

Add a new apartment detail view that will be displayed on a new sheet when clicking on a row from the apartment list.

### 📝 Todos

- [x] Show the details of the apartment.
- [x] Add the possibility to edit the details of the apartment.
- [x] Update the apartment addition view to use header save button.
