### ISSUE TITLE
Add map support

### ISSUE THREAD

**Issue by theo-brlle** [theo-brlle/homy#19]
### 🎯 Summary

Add the support of the map in the different views of the app.

### 📝 Todos

- [x] ~Show the search zone (districts) on the map.~ See #23 
- [x] Show a pin for each apartment depending of its status when the list is presented:
  - [x] Yellow pin for favorite apartments.
  - [x] Blue pin for upcoming visits.
  - [x] Red pin for recent visits.
- [x] Zoom the map on the specific pin when the apartment details view is presented.
