### ISSUE TITLE
Polish UI

### ISSUE THREAD

**Issue by theo-brlle** [theo-brlle/homy#29]
### 🎯 Summary

Polish the different UI components.

### 📝 Todos

- [ ] Polish the color of the sheets' close button.
- [ ] Polish the save button UI on the add apartment & apartment details views (make their height match the header height so it doesn't go bigger when appearing).
- [ ] Polish the action buttons on the details view (make them look more like Apple Maps buttons or closer to the SwiftUI `.bordered` button style).
