### ISSUE TITLE
Add CI workflow for PR guidelines compliance check

### ISSUE THREAD

**Issue by theo-brlle** [theo-brlle/homy#6]
### 🎯 Summary

Add a new **Pull Request - Guidelines compliance check** GitHub Actions workflow.

### 📝 Todos

- [ ] Check PR description
- [ ] Check branch name
- [ ] Check CONTRIBUTORS.md

### 🔗 Links

> - [GitHub Actions documentation](https://docs.github.com/fr/actions)
